### ISSUE TITLE
provide a context-specific alias for flatMap to assist in learning the API

### ISSUE THREAD

**Issue by jeremy-w** [bignerdranch/Deferred#21]
`flatMap` is a generic term that's great for people who can come at this from that level already, but does a disservice to people whose first exposure to something like this is `Deferred`. Providing a more deferred-specific API with a more suggestive name alongside `flatMap` would hopefully allow them to ramp up to understanding `flatMap` in this context.

Suggestions:

- `andEventually`
- `eventually`
- `whenResolved`
- `andThen`

The tricky part to me is that these all could just as well be read as aliases for `map`, since the difference between `map` and `flatMap` comes down to `map` returning a `Deferred<Value>` that's been resolved from the get-go, while `flatMap` allows you to return any flavor of `Deferred<Value>`.

**Comment by zwaldowski** [comment]
I think I'm able to be convinced the `map` and `flatMap` are the wrong names entirely. There's a slight conceptual mismatch with the stdlib (`map` and `flatMap` are used mostly for containers), as well as the signature differences (under 2.0, `rethrows`, etc.).

Let's reframe this suggestion around what we ultimately want the API to look like in terms of clarity and ease-of-use. Would a `Future` type have names `map` and `flatMap`?

**Comment by zwaldowski** [comment]
Ping @jjmanton for his opinions.

**Comment by jjmanton** [comment]
Any thoughts on C++/Boost futures? http://www.boost.org/doc/libs/1_55_0/doc/html/thread/synchronization.html#thread.synchronization.futures.reference.unique_future.then

They use method names like then, upon, unwrap.

**Comment by jeremy-w** [comment]
Some comments in the Boost docs link to [a proposal to improve C++11's std::future/std::shared_future](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3634.pdf); I found that document did a lot better job of explaining what the APIs were supposed to do and why. The proposal is inspired by Microsoft's Parallel Programming Libraries (PPL).

The overall model is more complicated than Deferred, and more synchronous; that last bit is what the  proposal doc that the Boost API is in the process of implementing is about fixing.

- You get a future either directly (`make_ready_future`) or from either a promise or a task.
- A promise can only be filled once (same as how Deferred works today).
- A future can only be gotten once. Getting it again triggers an exception.
  - You can work around this by making a shared future.
- A get is blocking.

So Future.get is Deferred.value (though .get has a version with a timeout parameter).

The C++ proposal adds API to enable writing non-blocking code with futures by adding:

- make_ready_future: as a convenience for when you know the value already
- ready: so you can avoid chaining a then closure when the value is already available (typical C++ perfhacking)
- then: so you can add a continuation closure; it looks like you can only add one, but this otherwise acts like a weird version of flapMap where the argument is a `Deferred<T>` rather than just `T`; this looks like it's because the future might hold an exception rather than a value
- when_any: waits for any to become ready, and then copies them all into a vector to pass to the continuation; note that the continuation just gets a pile of futures, and it then has to walk over them to pull out the data it needs
- when_all: same deal, but waits for them all to become ready
- unwrap: it's pretty easy to stack up futures, so you need some way to get an inner future out of an outer future, and that's what this provides. There's some discussion of how they decided not to automatically unwrap for you in any cases, though PPL does do this.

**Comment by zwaldowski** [comment]
I asked above to reframe with building #33 in mind. I find "learning helpers" distasteful because they a) imply the built-in methods are too hard to learn and b) would create an inconsistent style in a given project based around the author's experience. If `map` and `flatMap` don't make nearly immediate sense, we should name them differently.

With respect to the above comments (and the ones in #20 et. al.), I suggest we avoid sounding too much like English sentences - at least that's the feeling I get out of `andFoo` and such.

**Comment by zwaldowski** [comment]
The latest opinion, quote @randomstep: "Nope. Nope. No. No. No. Nope." He cites a recent bikeshedding on the Swift mailing lists about `Optional.map` and `Optional.flatMap`. I'll have him post that link because my mailing-list-fu is weak at present.

Though it's a magical multithreaded monad, it's still a monad. (I think.)

If we want to change the names, let's go ahead and change them. No aliases, though, it just confuses things.

**Comment by jeremy-w** [comment]
If Swift is going all-in on `flatMap`, works for me.

**Comment by randomstep** [comment]
The Nope response was in reaction to the "have aliased terms" idea. We should get the names correct, and then users can learn and use them.

I'm not strongly opposed to new names, but a relatively strong case has to be made that we've found more expressive names. Particularly in light of Swift's fully embracing map and flatMap. The specific message I was thinking of, with quotes from Radar responses:
https://lists.swift.org/pipermail/swift-evolution/2015-December/000066.html

This was in an effort to further bikeshed on flatMap naming on Optionals in Swift stdlib. There have been a few other threads attempting things along those lines as well. 

I don't have a great appetite for this particular bikeshed at the moment (here in Deferred), because I am presuming that people who will use Deferred will be learning the flatMap term anyway and will gain sufficient comfort that it is not a roadblock here.

**Comment by jeremy-w** [comment]
I was thinking along the lines of Evan Czaplicki's "let's be mainstream"
talk at CurryOn! Prague (https://www.youtube.com/watch?v=oYk8CKH7OhE), but
it's clear that ship has sailed for Swift (plus Apple have the clout to
force adoption of their chosen terminology as platform owner).

--
Jeremy W. Sherman <jeremy@bignerdranch.com>

2015-12-08 22:20 GMT-05:00 Step Christopher <notifications@github.com>:

**Comment by zwaldowski** [comment]
Hey, we did this for Swift 3! 😁 Symbolically re-opening and closing.
