### ISSUE TITLE
Swift 4.2 Compatibility for @_versioned

### ISSUE THREAD

**Issue by drumnkyle** [bignerdranch/Deferred#278]
`@_versioned` was renamed to `@usableFromInline` and there is another one you have used as well. If you just build, `Protected.swift` has the warnings. I made the changes locally, but also had other changes and don't know how you want to handle supporting 4.1 vs 4.2, so figured I'd just submit an issue.

**Comment by zwaldowski** [comment]
We appreciate the heads up!

Since we want Deferred to continue to offer compatibility with Swift 4.1, it is important to keep the old annotations in place. Furthermore, you can't `#if swift` them. See also apple/swift-nio#631.

It's not all bad news, though! In Swift 4.2 and 5.0, compiling Deferred in Swift 4.0 or Swift 4.1 language mode (using `SWIFT_VERSION`) should not show the warnings thanks to [SR-7578](https://bugs.swift.org/browse/SR-7578). Checking out Deferred from `master` doesn't warn; nor does embedding using CocoaPods, to my knowledge.

Please check your project and reopen the issue if there's any questions I can help answer about your setup.

**Comment by zwaldowski** [comment]
Aha! In that case feel free to follow Xcode’s fix-it’s. We’re excited to update the annotations as soon as Swift 5 hits the scene.
